#!/usr/bin/env python3
"""
法术描述翻译脚本 V3 - 增强版智能规则翻译
分批翻译 5e-SRD-Spells.json 中的法术描述
"""

import json
import re
import sys

# 扩展的术语翻译映射表
TRANSLATIONS = {
    # ===== 基础动词和助动词 =====
    "is": "是",
    "are": "是",
    "was": "是",
    "were": "是",
    "be": "是",
    "been": "是",
    "being": "是",
    "have": "拥有",
    "has": "拥有",
    "had": "拥有",
    "do": "做",
    "does": "做",
    "did": "做",
    "done": "完成",
    "can": "可以",
    "could": "可以",
    "will": "将",
    "would": "将",
    "shall": "应当",
    "should": "应该",
    "may": "可以",
    "might": "可能",
    "must": "必须",
    "shall": "将",
    
    # ===== 人称代词 =====
    "I": "我",
    "me": "我",
    "my": "我的",
    "mine": "我的",
    "you": "你",
    "your": "你的",
    "yours": "你的",
    "he": "他",
    "him": "他",
    "his": "他的",
    "she": "她",
    "her": "她的",
    "hers": "她的",
    "it": "它",
    "its": "它的",
    "its": "它的",
    "we": "我们",
    "us": "我们",
    "our": "我们的",
    "ours": "我们的",
    "they": "它们",
    "them": "它们",
    "their": "它们的",
    "theirs": "它们的",
    
    # ===== 指示代词 =====
    "this": "这个",
    "that": "那个",
    "these": "这些",
    "those": "那些",
    "such": "这样的",
    
    # ===== 疑问词和关系代词 =====
    "who": "谁",
    "whom": "谁",
    "whose": "谁的",
    "which": "哪个",
    "what": "什么",
    "whatever": "无论什么",
    "whoever": "无论谁",
    "whichever": "无论哪个",
    "where": "哪里",
    "when": "何时",
    "why": "为什么",
    "how": "如何",
    
    # ===== 冠词 =====
    "a": "一个",
    "an": "一个",
    "the": "该",
    
    # ===== 介词 =====
    "in": "在",
    "on": "在",
    "at": "在",
    "by": "通过",
    "with": "带有",
    "without": "没有",
    "from": "从",
    "to": "至",
    "into": "进入",
    "onto": "到...上",
    "out of": "离开",
    "off": "离开",
    "up": "向上",
    "down": "向下",
    "over": "在...上方",
    "under": "在...下方",
    "above": "在...上方",
    "below": "在...下方",
    "beneath": "在...下方",
    "before": "在...之前",
    "after": "在...之后",
    "behind": "在...后面",
    "in front of": "在...前面",
    "beside": "在...旁边",
    "next to": "在...旁边",
    "near": "靠近",
    "far from": "远离",
    "between": "在...之间",
    "among": "在...之中",
    "through": "穿过",
    "across": "横跨",
    "along": "沿着",
    "around": "围绕",
    "against": "对抗",
    "toward": "朝向",
    "towards": "朝向",
    "within": "在...之内",
    "inside": "在...内部",
    "outside": "在...外部",
    "beyond": "超出",
    "past": "经过",
    "via": "通过",
    "per": "每",
    "during": "在...期间",
    "throughout": "贯穿",
    "until": "直到",
    "till": "直到",
    "since": "自从",
    "for": "持续",
    "about": "关于",
    "of": "的",
    
    # ===== 连词 =====
    "and": "且",
    "or": "或",
    "but": "但",
    "yet": "然而",
    "so": "所以",
    "for": "因为",
    "because": "因为",
    "since": "因为",
    "as": "由于",
    "while": "当",
    "when": "当",
    "whenever": "每当",
    "if": "如果",
    "unless": "除非",
    "although": "虽然",
    "though": "虽然",
    "even if": "即使",
    "even though": "即使",
    "whether": "是否",
    "either": "要么",
    "neither": "既不",
    "both": "两者都",
    "not only": "不仅",
    "but also": "而且",
    
    # ===== 副词 =====
    "not": "不",
    "no": "无",
    "never": "从不",
    "always": "总是",
    "often": "经常",
    "sometimes": "有时",
    "usually": "通常",
    "rarely": "很少",
    "seldom": "很少",
    "frequently": "频繁地",
    "already": "已经",
    "yet": "还",
    "still": "仍然",
    "just": "刚刚",
    "only": "仅",
    "merely": "仅仅",
    "even": "甚至",
    "also": "也",
    "too": "也",
    "either": "也",
    "neither": "也不",
    "as well": "也",
    "instead": "代替",
    "rather": " rather",
    "else": "其他",
    "otherwise": "否则",
    "therefore": "因此",
    "thus": "因此",
    "hence": "因此",
    "consequently": "因此",
    "accordingly": "相应地",
    "however": "然而",
    "nevertheless": "尽管如此",
    "nonetheless": "尽管如此",
    "moreover": "此外",
    "furthermore": "此外",
    "besides": "此外",
    "additionally": "此外",
    "meanwhile": "与此同时",
    "afterwards": "之后",
    "later": "稍后",
    "soon": "很快",
    "immediately": "立即",
    "instantly": "立即",
    "suddenly": "突然",
    "gradually": "逐渐",
    "finally": "最终",
    "eventually": "最终",
    "initially": "最初",
    "originally": "原本",
    "previously": "之前",
    "formerly": " formerly",
    "currently": "当前",
    "presently": "目前",
    "recently": "最近",
    "lately": " lately",
    "here": "这里",
    "there": "那里",
    "everywhere": "到处",
    "somewhere": "某处",
    "nowhere": "无处",
    "anywhere": "任何地方",
    "elsewhere": "其他地方",
    "above": "上方",
    "below": "下方",
    "up": "向上",
    "down": "向下",
    "forward": "向前",
    "back": "向后",
    "backward": "向后",
    "ahead": " ahead",
    "behind": "后面",
    "around": "周围",
    "about": "大约",
    "approximately": "大约",
    "roughly": " roughly",
    "nearly": "几乎",
    "almost": "几乎",
    "practically": "几乎",
    "virtually": " virtually",
    "exactly": "确切地",
    "precisely": "精确地",
    "definitely": "肯定地",
    "certainly": "当然",
    "surely": " surely",
    "probably": "可能",
    "possibly": "可能",
    "perhaps": "也许",
    "maybe": "也许",
    "likely": " likely",
    "unlikely": "不太可能",
    "especially": "尤其",
    "particularly": " particularly",
    "specifically": " specifically",
    "mainly": " mainly",
    "mostly": " mostly",
    "largely": " largely",
    "partly": "部分地",
    "partially": " partially",
    "completely": "完全地",
    "totally": " totally",
    "entirely": " entirely",
    "wholly": " wholly",
    "fully": "完全地",
    "quite": " quite",
    "rather": " rather",
    "fairly": " fairly",
    "pretty": "相当",
    "very": "非常",
    "extremely": " extremely",
    "incredibly": " incredibly",
    "absolutely": " absolutely",
    "utterly": " utterly",
    "thoroughly": " thoroughly",
    "deeply": " deeply",
    "greatly": " greatly",
    "highly": " highly",
    "strongly": "强烈地",
    "weakly": " weakly",
    "hard": " hard",
    "hardly": " hardly",
    "barely": " barely",
    "scarcely": " scarcely",
    "enough": "足够",
    "sufficiently": " sufficiently",
    "adequately": " adequately",
    "properly": " properly",
    "correctly": " correctly",
    "wrongly": " wrongly",
    "badly": " badly",
    "poorly": " poorly",
    "well": " well",
    "better": "更好",
    "best": " best",
    "worse": "更糟",
    "worst": " worst",
    "more": "更多",
    "most": " most",
    "less": "更少",
    "least": "最少",
    "much": " much",
    "many": " many",
    "little": " little",
    "few": " few",
    "a lot of": "很多",
    "lots of": "很多",
    "plenty of": " plenty of",
    "a number of": "若干",
    "the number of": "...的数量",
    "a great deal of": "大量的",
    "a large amount of": "大量的",
    "a large number of": "大量的",
    "a small amount of": "少量的",
    "a small number of": "少量的",
    
    # ===== 形容词 =====
    "big": "大的",
    "large": "大的",
    "huge": "巨大的",
    "giant": "巨大的",
    "gigantic": "巨大的",
    "enormous": "巨大的",
    "immense": "巨大的",
    "vast": "广阔的",
    "massive": " massive",
    "great": "伟大的",
    "small": "小的",
    "little": "小的",
    "tiny": "微小的",
    "minute": "微小的",
    "miniature": "微型的",
    "slight": "轻微的",
    "minor": "次要的",
    "major": "主要的",
    "tall": "高的",
    "short": "矮的",
    "long": "长的",
    "brief": "简短的",
    "wide": "宽的",
    "narrow": "窄的",
    "thick": "厚的",
    "thin": "薄的",
    "deep": "深的",
    "shallow": "浅的",
    "high": "高的",
    "low": "低的",
    "fast": "快的",
    "slow": "慢的",
    "quick": "迅速的",
    "rapid": "快速的",
    "swift": "迅速的",
    "speedy": " speedily",
    "new": "新的",
    "old": "旧的",
    "young": "年轻的",
    "ancient": "古老的",
    "modern": "现代的",
    "current": "当前的",
    "present": " present",
    "past": "过去的",
    "future": "未来的",
    "early": "早期的",
    "late": "晚期的",
    "first": "第一",
    "last": "最后的",
    "final": "最终的",
    "initial": "最初的",
    "original": "原始的",
    "previous": "之前的",
    "following": " following",
    "next": "下一个",
    "subsequent": "随后的",
    "former": " former",
    "latter": " latter",
    "same": "相同的",
    "different": "不同的",
    "similar": "相似的",
    "various": "各种的",
    "diverse": " diverse",
    "distinct": " distinct",
    "unique": "独特的",
    "special": "特殊的",
    "particular": "特定的",
    "specific": " specific",
    "general": "一般的",
    "universal": "普遍的",
    "common": "常见的",
    "uncommon": "罕见的",
    "rare": "稀有的",
    "ordinary": "普通的",
    "normal": "正常的",
    "regular": " regular",
    "standard": "标准的",
    "average": " average",
    "usual": " usual",
    "unusual": "不寻常的",
    "strange": "奇怪的",
    "odd": " odd",
    "weird": " weird",
    "abnormal": "异常的",
    "extraordinary": "非凡的",
    "exceptional": " exceptional",
    "excellent": "优秀的",
    "good": "好的",
    "fine": " fine",
    "nice": " nice",
    "bad": "坏的",
    "evil": "邪恶的",
    "wicked": " wicked",
    "wrong": "错误的",
    "right": "正确的",
    "correct": "正确的",
    "accurate": "精确的",
    "exact": "确切的",
    "precise": "精确的",
    "clear": "清晰的",
    "obvious": "明显的",
    "evident": " evident",
    "apparent": " apparent",
    "visible": "可见的",
    "invisible": "不可见的",
    "hidden": "隐藏的",
    "secret": "秘密的",
    "open": "开放的",
    "closed": "关闭的",
    "free": "自由的",
    "busy": "忙碌的",
    "available": "可用的",
    "unavailable": "不可用的",
    "possible": "可能的",
    "impossible": "不可能的",
    "probable": "可能的",
    "likely": "可能的",
    "unlikely": "不太可能的",
    "certain": "确定的",
    "sure": "确定的",
    "uncertain": "不确定的",
    "doubtful": " doubtful",
    "true": "真实的",
    "false": "虚假的",
    "real": "真实的",
    "actual": "实际的",
    "fake": "假的",
    "false": "假的",
    "important": "重要的",
    "significant": "重要的",
    "essential": " essential",
    "vital": " vital",
    "crucial": " crucial",
    "critical": "关键的",
    "necessary": "必要的",
    "needed": "需要的",
    "required": "必需的",
    "unnecessary": "不必要的",
    "useless": "无用的",
    "helpful": "有帮助的",
    "useful": "有用的",
    "beneficial": "有益的",
    "harmful": "有害的",
    "dangerous": "危险的",
    "safe": "安全的",
    "secure": "安全的",
    "risky": " risky",
    "deadly": "致命的",
    "fatal": "致命的",
    "lethal": "致命的",
    "powerful": "强大的",
    "strong": "强壮的",
    "mighty": " mighty",
    "forceful": " forceful",
    "potent": " potent",
    "weak": "虚弱的",
    "feeble": " feeble",
    "fragile": "脆弱的",
    "frail": " frail",
    "delicate": " delicate",
    "hard": "坚硬的",
    "soft": "柔软的",
    "solid": "固体的",
    "liquid": "液体的",
    "gas": "气体的",
    "firm": " firm",
    "stiff": "僵硬的",
    "flexible": "灵活的",
    "elastic": "弹性的",
    "plastic": " plastic",
    "smooth": "光滑的",
    "rough": "粗糙的",
    "sharp": "锋利的",
    "blunt": "钝的",
    "pointed": "尖的",
    "round": "圆的",
    "flat": "平的",
    "level": "水平的",
    "straight": "直的",
    "curved": "弯曲的",
    "crooked": " crooked",
    "bent": "弯曲的",
    "twisted": "扭曲的",
    "loose": "松的",
    "tight": "紧的",
    "wet": "湿的",
    "dry": "干的",
    "hot": "热的",
    "cold": "冷的",
    "warm": "温暖的",
    "cool": "凉爽的",
    "fresh": "新鲜的",
    "stale": " stale",
    "clean": "干净的",
    "dirty": "脏的",
    "pure": "纯净的",
    "impure": " impure",
    "clear": "清澈的",
    "cloudy": " cloudy",
    "bright": "明亮的",
    "dark": "黑暗的",
    "light": "轻的",
    "heavy": "重的",
    "full": "满的",
    "empty": "空的",
    "complete": "完整的",
    "incomplete": "不完整的",
    "whole": "整个的",
    "partial": "部分的",
    "total": "总计的",
    "equal": "相等的",
    "unequal": " unequal",
    "same": "相同的",
    "different": "不同的",
    "similar": "相似的",
    "alike": " alike",
    "unlike": " unlike",
    "related": "相关的",
    "unrelated": "无关的",
    "connected": "连接的",
    "disconnected": "断开的",
    "joined": " joined",
    "separate": "分开的",
    "single": "单个的",
    "double": "双倍的",
    "triple": "三倍的",
    "multiple": "多个的",
    "alone": "单独的",
    "only": "唯一的",
    "sole": " sole",
    "unique": "独特的",
    "individual": " individual",
    "personal": "个人的",
    "private": "私人的",
    "public": "公共的",
    "common": "共同的",
    "shared": "共享的",
    "mutual": " mutual",
    "joint": " joint",
    "collective": "集体的",
    "active": "活跃的",
    "inactive": "不活跃的",
    "busy": "忙碌的",
    "idle": "空闲的",
    "working": "工作的",
    "functioning": " functioning",
    "operating": " operating",
    "running": "运行的",
    "moving": "移动的",
    "still": "静止的",
    "motionless": " motionless",
    "stationary": " stationary",
    "alive": "活着的",
    "dead": "死亡的",
    "living": "活着的",
    "live": " live",
    "existing": "存在的",
    "extinct": "灭绝的",
    "aware": " aware",
    "unaware": " unaware",
    "conscious": "有意识的",
    "unconscious": "无意识的",
    "asleep": "睡着的",
    "awake": "醒着的",
    "alert": "警觉的",
    "watchful": " watchful",
    "careful": "小心的",
    "cautious": "谨慎的",
    "careless": "粗心的",
    "reckless": "鲁莽的",
    "safe": "安全的",
    "dangerous": "危险的",
    "risky": " risky",
    "hazardous": " hazardous",
    "harmful": "有害的",
    "harmless": "无害的",
    "innocent": "无辜的",
    "guilty": "有罪的",
    "legal": "合法的",
    "illegal": "非法的",
    "lawful": "守法的",
    "lawless": " lawless",
    "allowed": "允许的",
    "permitted": " permitted",
    "forbidden": "禁止的",
    "prohibited": "禁止的",
    "banned": " banned",
    "acceptable": "可接受的",
    "unacceptable": "不可接受的",
    "satisfactory": "满意的",
    "unsatisfactory": "不满意的",
    "adequate": "足够的",
    "inadequate": "不足的",
    "sufficient": "充分的",
    "insufficient": "不足的",
    "enough": "足够的",
    "plenty": "充足的",
    "scarce": "稀缺的",
    "abundant": "丰富的",
    "plentiful": " plentiful",
    "rich": "富有的",
    "poor": "贫穷的",
    "wealthy": " wealthy",
    "needy": " needy",
    "expensive": "昂贵的",
    "cheap": "便宜的",
    "costly": " costly",
    "priceless": "无价的",
    "worthless": " worthless",
    "valuable": "有价值的",
    "invaluable": " invaluable",
    "precious": "珍贵的",
    "dear": " dear",
    "beautiful": "美丽的",
    "pretty": "漂亮的",
    "lovely": "可爱的",
    "handsome": "英俊的",
    "attractive": "有吸引力的",
    "gorgeous": " gorgeous",
    "stunning": " stunning",
    "ugly": "丑陋的",
    "hideous": " hideous",
    "horrible": "可怕的",
    "terrible": "糟糕的",
    "awful": " awful",
    "dreadful": " dreadful",
    "wonderful": "精彩的",
    "marvelous": " marvelous",
    "fantastic": "极好的",
    "excellent": "优秀的",
    "outstanding": " outstanding",
    "remarkable": " remarkable",
    "extraordinary": "非凡的",
    "amazing": "惊人的",
    "astonishing": " astonishing",
    "surprising": "令人惊讶的",
    "shocking": " shocking",
    "startling": " startling",
    "pleasant": "愉快的",
    "unpleasant": "不愉快的",
    "enjoyable": " enjoyable",
    "disagreeable": " disagreeable",
    "comfortable": "舒适的",
    "uncomfortable": "不舒适的",
    "convenient": "方便的",
    "inconvenient": "不方便的",
    "easy": "容易的",
    "difficult": "困难的",
    "hard": "困难的",
    "simple": "简单的",
    "complicated": "复杂的",
    "complex": "复杂的",
    "straightforward": " straightforward",
    "troublesome": " troublesome",
    "problematic": "有问题的",
    "tough": "艰难的",
    "challenging": "有挑战性的",
    "demanding": " demanding",
    "effortless": "毫不费力的",
    "automatic": "自动的",
    "manual": "手动的",
    "natural": "自然的",
    "artificial": "人造的",
    "synthetic": "合成的",
    "fake": "假的",
    "genuine": "真正的",
    "authentic": " authentic",
    "original": "原始的",
    "copy": "复制的",
    "familiar": "熟悉的",
    "unfamiliar": "不熟悉的",
    "known": "已知的",
    "unknown": "未知的",
    "famous": "著名的",
    "infamous": " infamous",
    "well-known": " well-known",
    "obscure": " obscure",
    "popular": "流行的",
    "unpopular": "不流行的",
    "common": "常见的",
    "rare": "稀有的",
    "frequent": "频繁的",
    "infrequent": " infrequent",
    "regular": "规律的",
    "irregular": "不规则的",
    "consistent": "一致的",
    "inconsistent": "不一致的",
    "constant": "恒定的",
    "variable": "可变的",
    "changing": "变化的",
    "unchanging": "不变的",
    "stable": "稳定的",
    "unstable": "不稳定的",
    "steady": " steady",
    "shaky": "摇晃的",
    "solid": "固体的",
    "liquid": "液体的",
    "gaseous": "气体的",
    "hard": "坚硬的",
    "soft": "柔软的",
    "rigid": " rigid",
    "flexible": "灵活的",
    "stiff": "僵硬的",
    "elastic": "弹性的",
    "plastic": " plastic",
    "breakable": "易碎的",
    "unbreakable": " unbreakable",
    "fragile": "脆弱的",
    "strong": "强壮的",
    "weak": "虚弱的",
    "tough": "坚韧的",
    "tender": " tender",
    "gentle": "温柔的",
    "rough": "粗暴的",
    "violent": "暴力的",
    "fierce": "凶猛的",
    "wild": " wild",
    "tame": " tame",
    "domestic": " domestic",
    "civilized": "文明的",
    "primitive": "原始的",
    "advanced": "先进的",
    "backward": " backward",
    "developed": " developed",
    "developing": " developing",
    "underdeveloped": " underdeveloped",
    "mature": "成熟的",
    "immature": " immature",
    "ripe": " ripe",
    "unripe": " unripe",
    "raw": "生的",
    "cooked": "煮熟的",
    "done": "完成的",
    "ready": "准备好的",
    "prepared": "准备好的",
    "unprepared": "未准备的",
    "willing": "自愿的",
    "unwilling": "非自愿的",
    "eager": "渴望的",
    "reluctant": "不情愿的",
    "hesitant": "犹豫的",
    "keen": " keen",
    "enthusiastic": "热情的",
    "indifferent": " indifferent",
    "interested": "感兴趣的",
    "uninterested": "不感兴趣的",
    "curious": "好奇的",
    "bored": "无聊的",
    "excited": "兴奋的",
    "calm": "平静的",
    "peaceful": "和平的",
    "quiet": "安静的",
    "noisy": "吵闹的",
    "loud": "大声的",
    "silent": "寂静的",
    "still": "静止的",
    "restless": " restless",
    "nervous": "紧张的",
    "anxious": "焦虑的",
    "worried": "担心的",
    "concerned": " concerned",
    "afraid": "害怕的",
    "scared": "恐惧的",
    "frightened": "恐慌的",
    "terrified": " terrified",
    "horrified": " horrified",
    "panicked": " panicked",
    "brave": "勇敢的",
    "courageous": " courageous",
    "bold": "大胆的",
    "fearless": "无畏的",
    "confident": "自信的",
    "sure": "确定的",
    "certain": "确定的",
    "uncertain": "不确定的",
    "doubtful": " doubtful",
    "suspicious": "可疑的",
    "doubtful": " doubtful",
    "skeptical": " skeptical",
    "trusting": "信任的",
    "distrustful": " distrustful",
    "suspicious": " suspicious",
    "loyal": "忠诚的",
    "faithful": " faithful",
    "devoted": " devoted",
    "dedicated": " dedicated",
    "committed": " committed",
    "unfaithful": "不忠的",
    "disloyal": " disloyal",
    "treacherous": " treacherous",
    "honest": "诚实的",
    "truthful": " truthful",
    "sincere": "真诚的",
    "dishonest": "不诚实的",
    "lying": "说谎的",
    "deceitful": " deceitful",
    "false": "虚假的",
    "true": "真实的",
    "real": "真实的",
    "actual": "实际的",
    "genuine": "真正的",
    "authentic": " authentic",
    "original": "原始的",
    "fake": "假的",
    "false": "假的",
    "artificial": "人造的",
    "synthetic": "合成的",
    "natural": "自然的",
    "physical": " physical",
    "mental": "精神的",
    "spiritual": " spiritual",
    "material": " material",
    "immaterial": " immaterial",
    "visible": "可见的",
    "invisible": "不可见的",
    "seen": "看见的",
    "unseen": "未看见的",
    "noticed": "注意到的",
    "unnoticed": "未被注意的",
    "observed": "观察到的",
    "hidden": "隐藏的",
    "concealed": " concealed",
    "secret": "秘密的",
    "open": "开放的",
    "obvious": "明显的",
    "apparent": " apparent",
    "evident": " evident",
    "clear": "清晰的",
    "unclear": "不清晰的",
    "vague": "模糊的",
    "ambiguous": " ambiguous",
    "precise": "精确的",
    "exact": "确切的",
    "accurate": "准确的",
    "correct": "正确的",
    "right": "正确的",
    "wrong": "错误的",
    "incorrect": "不正确的",
    "mistaken": "错误的",
    "false": "错误的",
    "true": "正确的",
    "valid": "有效的",
    "invalid": "无效的",
    "legal": "合法的",
    "illegal": "非法的",
    "lawful": "守法的",
    "chaotic": "混乱的",
    "good": "善良的",
    "evil": "邪恶的",
    "neutral": "中立的",
    "magical": "魔法的",
    "nonmagical": "非魔法的",
    "supernatural": "超自然的",
    "mundane": "平凡的",
    "ordinary": "普通的",
    "extraordinary": "非凡的",
    "special": "特殊的",
    "particular": "特定的",
    "specific": "具体的",
    "general": "一般的",
    "universal": "普遍的",
    "local": "当地的",
    "global": "全球的",
    "national": "国家的",
    "international": "国际的",
    "internal": "内部的",
    "external": "外部的",
    "inner": " inner",
    "outer": " outer",
    "upper": " upper",
    "lower": " lower",
    "higher": "更高的",
    "lower": "更低的",
    "superior": " superior",
    "inferior": " inferior",
    "senior": " senior",
    "junior": " junior",
    "primary": "主要的",
    "secondary": "次要的",
    "main": "主要的",
    "minor": "次要的",
    "major": "主要的",
    "chief": " chief",
    "principal": " principal",
    "central": " central",
    "basic": "基本的",
    "fundamental": " fundamental",
    "essential": " essential",
    "vital": " vital",
    "crucial": " crucial",
    "critical": "关键的",
    "key": "关键的",
    "central": " central",
    "core": "核心的",
    "nuclear": " nuclear",
    "peripheral": " peripheral",
    "marginal": " marginal",
    "minor": "次要的",
    "trivial": " trivial",
    "insignificant": " insignificant",
    "unimportant": "不重要的",
    "important": "重要的",
    "significant": "重要的",
    "meaningful": " meaningful",
    "meaningless": " meaningless",
    "useful": "有用的",
    "useless": "无用的",
    "helpful": "有帮助的",
    "helpless": "无助的",
    "beneficial": "有益的",
    "harmful": "有害的",
    "advantageous": " advantageous",
    "disadvantageous": " disadvantageous",
    "profitable": " profitable",
    "unprofitable": " unprofitable",
    "productive": " productive",
    "unproductive": " unproductive",
    "effective": "有效的",
    "ineffective": "无效的",
    "efficient": "高效的",
    "inefficient": "低效的",
    "active": "活跃的",
    "inactive": "不活跃的",
    "positive": "积极的",
    "negative": "消极的",
    "optimistic": "乐观的",
    "pessimistic": "悲观的",
    "hopeful": "有希望的",
    "hopeless": "无望的",
    "successful": "成功的",
    "unsuccessful": "不成功的",
    "victorious": " victorious",
    "defeated": " defeated",
    "triumphant": " triumphant",
    "happy": "快乐的",
    "unhappy": "不快乐的",
    "sad": "悲伤的",
    "joyful": " joyful",
    "cheerful": " cheerful",
    "melancholy": " melancholy",
    "depressed": "沮丧的",
    "elated": " elated",
    "excited": "兴奋的",
    "thrilled": " thrilled",
    "delighted": " delighted",
    "pleased": "高兴的",
    "satisfied": "满意的",
    "content": "满足的",
    "displeased": "不高兴的",
    "dissatisfied": "不满意的",
    "discontent": "不满的",
    "angry": "愤怒的",
    "mad": "疯狂的",
    "furious": " furious",
    "irate": " irate",
    "annoyed": "恼怒的",
    "irritated": " irritated",
    "bothered": " bothered",
    "troubled": " troubled",
    "disturbed": " disturbed",
    "upset": " upset",
    "worried": "担心的",
    "concerned": " concerned",
    "anxious": "焦虑的",
    "nervous": "紧张的",
    "tense": "紧张的",
    "relaxed": "放松的",
    "calm": "平静的",
    "peaceful": "和平的",
    "serene": " serene",
    "tranquil": " tranquil",
    "quiet": "安静的",
    "still": "静止的",
    "restless": " restless",
    "agitated": " agitated",
    "excited": "兴奋的",
    "aroused": " aroused",
    "stimulated": "刺激的",
    "bored": "无聊的",
    "tired": "疲倦的",
    "exhausted": "筋疲力尽的",
    "weary": " weary",
    "fatigued": "疲劳的",
    "sleepy": "困倦的",
    "drowsy": " drowsy",
    "awake": "醒着的",
    "asleep": "睡着的",
    "conscious": "有意识的",
    "unconscious": "无意识的",
    "aware": " aware",
    "unaware": " unaware",
    "sensible": " sensible",
    "sensitive": "敏感的",
    "insensitive": " insensitive",
    "responsive": " responsive",
    "unresponsive": "无反应的",
    "reactive": " reactive",
    "active": "活跃的",
    "passive": "被动的",
    "aggressive": "侵略性的",
    "defensive": "防御性的",
    "protective": "保护性的",
    "destructive": "破坏性的",
    "constructive": "建设性的",
    "creative": "创造性的",
    "imaginative": " imaginative",
    "inventive": " inventive",
    "original": "原始的",
    "novel": " novel",
    "new": "新的",
    "fresh": "新鲜的",
    "stale": " stale",
    "old": "旧的",
    "ancient": "古老的",
    "antique": " antique",
    "modern": "现代的",
    "contemporary": "当代的",
    "current": "当前的",
    "present": " present",
    "past": "过去的",
    "future": "未来的",
    "early": "早期的",
    "late": "晚期的",
    "ancient": "古老的",
    "medieval": "中世纪的",
    "primitive": "原始的",
    "advanced": "先进的",
    "developed": " developed",
    "developing": " developing",
    "underdeveloped": " underdeveloped",
    "industrial": "工业的",
    "agricultural": "农业的",
    "commercial": "商业的",
    "financial": "金融的",
    "economic": "经济的",
    "political": "政治的",
    "social": "社会的",
    "cultural": "文化的",
    "religious": "宗教的",
    "spiritual": "精神的",
    "mental": "精神的",
    "physical": " physical",
    "bodily": " bodily",
    "corporal": " corporal",
    "material": " material",
    "substantial": " substantial",
    "concrete": " concrete",
    "abstract": "抽象的",
    "theoretical": " theoretical",
    "practical": "实际的",
    "applied": "应用的",
    "pure": "纯净的",
    "mixed": "混合的",
    "combined": "结合的",
    "joined": " joined",
    "united": " united",
    "separated": "分开的",
    "divided": " divided",
    "split": " split",
    "broken": "破碎的",
    "damaged": "损坏的",
    "destroyed": "被摧毁的",
    "ruined": " ruined",
    "wrecked": " wrecked",
    "demolished": " demolished",
    "annihilated": " annihilated",
    "extinct": "灭绝的",
    "dead": "死亡的",
    "alive": "活着的",
    "living": "活着的",
    "live": " live",
    "animated": " animated",
    "inanimate": " inanimate",
    "lifeless": " lifeless",
    "animate": " animate",
}

# 游戏特定术语
GAME_TERMS = {
    # 动作
    "action": "动作",
    "actions": "动作",
    "bonus action": "附赠动作",
    "bonus actions": "附赠动作",
    "reaction": "反应",
    "reactions": "反应",
    "free action": "免费动作",
    "movement": "移动力",
    
    # 判定
    "saving throw": "豁免",
    "saving throws": "豁免",
    "ability check": "属性检定",
    "skill check": "技能检定",
    "spell attack": "法术攻击",
    "attack roll": "攻击检定",
    "damage roll": "伤害检定",
    "concentration check": "专注检定",
    
    # 资源
    "spell slot": "法术位",
    "spell slots": "法术位",
    "hit point": "生命值",
    "hit points": "生命值",
    "temporary hit points": "临时生命值",
    "hit point maximum": "生命值上限",
    "current hit points": "当前生命值",
    
    # 距离
    "range": "射程",
    "reach": "触及",
    "touch": "接触",
    "self": "自身",
    "sight": "视野",
    "feet": "尺",
    "foot": "尺",
    "melee": "近战",
    "ranged": "远程",
    
    # 时间
    "duration": "持续时间",
    "casting time": "施法时间",
    "instantaneous": "立即",
    "round": "回合",
    "rounds": "回合",
    "turn": "轮",
    "turns": "轮",
    "minute": "分钟",
    "minutes": "分钟",
    "hour": "小时",
    "hours": "小时",
    "day": "日",
    "days": "日",
    
    # 专注
    "concentration": "专注",
    "concentrating": "专注",
    
    # 伤害类型
    "bludgeoning damage": "钝击伤害",
    "piercing damage": "穿刺伤害",
    "slashing damage": "挥砍伤害",
    "acid damage": "强酸伤害",
    "cold damage": "冷冻伤害",
    "fire damage": "火焰伤害",
    "force damage": "力场伤害",
    "lightning damage": "闪电伤害",
    "necrotic damage": "黯蚀伤害",
    "poison damage": "毒素伤害",
    "psychic damage": "心灵伤害",
    "radiant damage": "光耀伤害",
    "thunder damage": "雷鸣伤害",
    
    # 生物类型
    "creature": "生物",
    "creatures": "生物",
    "humanoid": "类人生物",
    "beast": "野兽",
    "undead": "不死生物",
    "construct": "构装生物",
    "fiend": "邪魔",
    "celestial": "天界生物",
    "fey": "精类",
    "elemental": "元素生物",
    "dragon": "龙",
    "aberration": "异怪",
    "ooze": "泥怪",
    "plant": "植物",
    "monstrosity": "怪兽",
    "giant": "巨人",
    
    # 体型
    "Tiny": "微型",
    "Small": "小型",
    "Medium": "中型",
    "Large": "大型",
    "Huge": "巨型",
    "Gargantuan": "超巨型",
    
    # 属性
    "Strength": "力量",
    "Dexterity": "敏捷",
    "Constitution": "体质",
    "Intelligence": "智力",
    "Wisdom": "感知",
    "Charisma": "魅力",
    "str": "力量",
    "dex": "敏捷",
    "con": "体质",
    "int": "智力",
    "wis": "感知",
    "cha": "魅力",
    
    # 法术相关
    "spell": "法术",
    "spells": "法术",
    "cantrip": "戏法",
    "cantrips": "戏法",
    "ritual": "仪式",
    "magic": "魔法",
    "magical": "魔法的",
    "nonmagical": "非魔法的",
    "arcane": "奥术",
    "divine": "神圣",
    "spell level": "法术环阶",
    "spellcasting ability": "施法属性",
    "spellcasting ability modifier": "施法属性调整值",
    "spell save DC": "法术豁免DC",
    
    # 组件
    "component": "成分",
    "components": "成分",
    "verbal": "言语",
    "somatic": "姿势",
    "material": "材料",
    
    # 效果
    "target": "目标",
    "targets": "目标",
    "effect": "效果",
    "effects": "效果",
    "area": "区域",
    "radius": "半径",
    "cube": "立方体",
    "sphere": "球体",
    "cone": "锥形",
    "line": "线形",
    "cylinder": "圆柱",
    "wall": "墙",
    
    # 状态
    "charmed": "魅惑",
    "frightened": "恐慌",
    "paralyzed": "麻痹",
    "poisoned": "中毒",
    "blinded": "目盲",
    "deafened": "耳聋",
    "prone": "倒地",
    "grappled": "被擒抱",
    "restrained": "被束缚",
    "stunned": "被震慑",
    "unconscious": "昏迷",
    "incapacitated": "失能",
    "invisible": "隐形",
    "exhaustion": "力竭",
    
    # 其他
    "ally": "盟友",
    "allies": "盟友",
    "enemy": "敌人",
    "enemies": "敌人",
    "object": "物体",
    "objects": "物体",
    "weapon": "武器",
    "weapons": "武器",
    "armor": "护甲",
    "shield": "盾牌",
    "equipment": "装备",
    "gear": "装备",
    "item": "物品",
    "items": "物品",
    
    # 视觉
    "vision": "视觉",
    "darkvision": "黑暗视觉",
    "blindsight": "盲视",
    "truesight": "真实视觉",
    
    # 移动
    "speed": "速度",
    "walking speed": "步行速度",
    "flying speed": "飞行速度",
    "swimming speed": "游泳速度",
    "climbing speed": "攀爬速度",
    "hover": "悬浮",
    "teleport": "传送",
    "teleportation": "传送",
    
    # 优势劣势
    "advantage": "优势",
    "disadvantage": "劣势",
    "proficiency": "熟练",
    "expertise": "专精",
}

# 合并所有翻译
ALL_TRANSLATIONS = {**TRANSLATIONS, **GAME_TERMS}

# 需要保持原样的模式
PROTECTED_PATTERNS = [
    r'\bDC\s*\d+',  # DC 15
    r'\d+d\d+(?:\s*\+\s*\d+)?',  # 2d6, 4d4+2
    r'\+\d+\s+to\s+hit',  # +8 to hit
    r'\d+\s*(?:ft\.?|feet|foot)',  # 30 feet
    r'\d+\s*(?:minute|hour|day|round|turn)s?',  # 10 minutes
    r'\d+\s*(?:gp|sp|cp)',  # 25gp
    r'\d+\s*mile',  # 1 mile
    r'\bAC\s*\d+',  # AC 20
    r'\d+\s*级',  # 5级
    r'\d+\s*环',  # 3环
    r'\d+\s*hp',  # 25 hp
    r'\d+\s*HP',  # 25 HP
    r'\d+%',  # 50%
    r'\+\d+',  # +1
    r'-\d+',  # -1
]

def smart_translate(text):
    """智能翻译文本"""
    if not text or not isinstance(text, str):
        return text
    
    # 保护 Markdown 格式和特殊内容
    placeholders = []
    protected_text = text
    
    # 保护 Markdown 格式
    patterns_to_protect = [
        (r'\*\*\*[^*]+\*\*\*', '***'),  # bold italic headers
        (r'\*\*[^*]+\*\*', '**'),       # bold
        (r'\*[^*]+\*', '*'),            # italic
        (r'`[^`]+`', '`'),              # code
        (r'\[[^\]]+\]\([^)]+\)', '[]()'), # links
        (r'\|[^|]+\|', '|'),            # table cells
        (r'[-]+', '---'),               # table separators
        (r'#+\s+', '# '),               # headers
    ]
    
    for pattern, prefix in patterns_to_protect:
        matches = re.finditer(pattern, protected_text)
        for match in matches:
            placeholder = f"__P{len(placeholders)}__"
            placeholders.append((placeholder, match.group()))
            protected_text = protected_text.replace(match.group(), placeholder, 1)
    
    # 保护特定模式
    for pattern in PROTECTED_PATTERNS:
        matches = re.finditer(pattern, protected_text, re.IGNORECASE)
        for match in matches:
            placeholder = f"__P{len(placeholders)}__"
            placeholders.append((placeholder, match.group()))
            protected_text = protected_text.replace(match.group(), placeholder, 1)
    
    # 翻译 - 按长度降序以避免部分匹配
    translated = protected_text
    for en, zh in sorted(ALL_TRANSLATIONS.items(), key=lambda x: -len(x[0])):
        # 使用词边界进行精确匹配
        pattern = r'\b' + re.escape(en) + r'\b'
        translated = re.sub(pattern, zh, translated, flags=re.IGNORECASE)
    
    # 恢复保护的内容
    for placeholder, original in placeholders:
        translated = translated.replace(placeholder, original, 1)
    
    # 后处理：清理多余空格
    translated = re.sub(r'\s+', ' ', translated).strip()
    
    return translated


def translate_spell(spell):
    """翻译单个法术"""
    # 翻译 desc
    if 'desc_en' in spell and spell['desc_en']:
        if 'desc' not in spell:
            spell['desc'] = []
        # 确保长度一致
        while len(spell['desc']) < len(spell['desc_en']):
            spell['desc'].append('')
        for i, text in enumerate(spell['desc_en']):
            if i < len(spell['desc']):
                spell['desc'][i] = smart_translate(text)
    
    # 翻译 higher_level
    if 'higher_level_en' in spell and spell['higher_level_en']:
        if 'higher_level' not in spell:
            spell['higher_level'] = []
        while len(spell['higher_level']) < len(spell['higher_level_en']):
            spell['higher_level'].append('')
        for i, text in enumerate(spell['higher_level_en']):
            if i < len(spell['higher_level']):
                spell['higher_level'][i] = smart_translate(text)
    
    # 翻译 material
    if 'material_en' in spell and spell['material_en']:
        spell['material'] = smart_translate(spell['material_en'])
    
    return spell


def process_spells(input_file, output_file, level_min=None, level_max=None):
    """处理法术文件"""
    with open(input_file, 'r', encoding='utf-8') as f:
        spells = json.load(f)
    
    # 筛选指定等级的法术
    if level_min is not None and level_max is not None:
        target_spells = [s for s in spells if level_min <= s.get('level', 0) <= level_max]
    else:
        target_spells = spells
    
    print(f"Translating {len(target_spells)} spells (level {level_min}-{level_max})...")
    
    # 翻译每个法术
    for i, spell in enumerate(target_spells):
        # 在原数组中找到并更新
        for j, s in enumerate(spells):
            if s.get('index') == spell.get('index'):
                spells[j] = translate_spell(s)
                break
        
        if (i + 1) % 10 == 0 or (i + 1) == len(target_spells):
            print(f"  Progress: {i + 1}/{len(target_spells)}")
    
    # 保存结果
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(spells, f, ensure_ascii=False, indent=2)
    
    return len(target_spells)


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: python translate_spells_v3.py <batch_number>")
        print("  batch 1: cantrips + level 1-2 (127 spells)")
        print("  batch 2: level 3-5 (110 spells)")
        print("  batch 3: level 6-9 (82 spells)")
        print("  batch all: all spells (319 spells)")
        sys.exit(1)
    
    batch = sys.argv[1]
    input_file = 'src/2014-zh/5e-SRD-Spells.json'
    output_file = 'src/2014-zh/5e-SRD-Spells.json'
    
    if batch == "1":
        count = 0
        count += process_spells(input_file, output_file, 0, 0)
        count += process_spells(input_file, output_file, 1, 2)
        print(f"\n=== Batch 1 complete: {count} spells ===")
    elif batch == "2":
        count = process_spells(input_file, output_file, 3, 5)
        print(f"\n=== Batch 2 complete: {count} spells ===")
    elif batch == "3":
        count = process_spells(input_file, output_file, 6, 9)
        print(f"\n=== Batch 3 complete: {count} spells ===")
    elif batch == "all":
        count = process_spells(input_file, output_file, 0, 9)
        print(f"\n=== All batches complete: {count} spells ===")
    else:
        print(f"Unknown batch: {batch}")
        sys.exit(1)
